---
- name: deploy torb/portal
  become: yes
  become_user: isucon
  copy:
    src: ../../../../portal
    dest: /home/isucon/torb/
    owner: isucon
    group: isucon

- name: chown torb/portal
  become: yes
  become_user: root
  file:
    dest: /home/isucon/torb/portal
    owner: isucon
    group: isucon
    mode: u=rwX,g=rX,o=rX
    recurse: yes
